### ISSUE TITLE
Thread safety issues?

### ISSUE THREAD

**Issue by PJB3005** [Robmaister/SharpFont#128]
I've ran into some weird issues I can only chalk up to thread safety / race conditions. I didn't do much digging into the code yet but I'm posting this anyways in case you have any insight.

For what it's worth, I'm on Linux with FreeType 2.9.1. 

So uh, the first problem I had was that trying to load glyph metrics lazily seemed to cause bogus results on the glyph metrics and even exceptions from FreeType's font hinter. Basically I was building a font atlas for rendering with OpenGL ahead of time, but I wasn't loading the glyph metrics for advance etc until said glyph was first drawn (I was caching the metrics in my own struct after that).

Inconsistently and depending on whether I had drawn text before text would either render at all, or the glyph metrics would be all over the place, or FreeType would just randomely throw exceptions all with error codes relating to the TrueType font hinter.

Interestingly, a friend of mine on Windows with the build from SharpFont.Dependencies did not have this problem at all.

I chalked this up to me misusing FreeType and just cached the metrics ahead of time which did work without issue.

And then a few weeks later I ran into issue 2:

I was messing with my UI theme, and then suddenly loading a specific font at size 48 caused a segfault inside FreeType *upon loading the next font*. Any size above 40 caused this.

So I poked around to check if this size 41 font was being rendered into the font atlas correctly, I dumped the atlas file to disk with a quick `atlas.Save($"font-{face.FamilyName}-{size}.png");` aaand... it didn't crash anymore. This save is being done with ImageSharp for what it's worth, so it should be completely independent.

In fact, size 48 was still crashing, but saving the atlas to disk multiple times made that work too.

This leads me to believe there's a thread safety issue or something else related to the GC inside the library, since saving the image really cannot influence anything else. It might also explain why my first problem didn't happen on Windows, the .NET Framework GC might act differently.

I am not calling this library from a multithreaded context by the way. The only thing that might be is the GC's finalizer thread, and I couldn't find any safe guards against data races in, for example, the deconstructor of `Face`.

**Comment by PJB3005** [comment]
Turning OFF the GC with `MONO_GC_DEBUG="disable-minor,disable-major"` indeed seems to prevent the crash too. Furthermore it seems like Mono dies inside the finalizer for `FTBitmap` from `MONO_GC_DEBUG="log-finalizers"`

**Comment by Robmaister** [comment]
You might be right about a thread safety issue somewhere. The finalizers follow [the Dispose pattern](https://docs.microsoft.com/en-us/dotnet/standard/garbage-collection/implementing-dispose) which should avoid most issues, but won't correctly handle two threads calling Dispose at the same time. The finalizer won't be called until after the last reference to the object is gone, so there's no chance that a finalizer and Dispose call would interact in a way that causes race conditions.

If you've set up synchronization such that you finish all your FreeType work before calling dispose (or letting the GC take care of it), then SharpFont should have the same thread safety guarantees as FreeType.

I'm not really actively working on this project any more, it could be a small API difference causing larger issues between the last version I built and tested (2.6) and the current version you're trying to use (2.9.1). Installing an older version from your package manager would be a simple test to rule that issue out. Might also explain why your friend on Windows hasn't had any issues if API compatibility is the issue.

Also as a side note, the SharpFont.Dependencies repo exists mainly to build against different MSVC versions (which I believe can be avoided by statically linking to the CRT), and to fix a sizing issue - `long` always being 32 bits wide on Windows (most other platforms make `long` 64 bits wide when running on x64). Some other languages have an interop type that follows these rules, but C# does not (at least not when I was working on this project, haven't kept up with .NET Core).

I can provide some guidance, but your best bet would be to strip down your code to the simplest it can possibly be while still exhibiting the issue and analyzing that more closely.

**Comment by PJB3005** [comment]
Welp.

```cs
/// <param name="bufferPtr">A pointer to a buffer of a loaded file. Must not be freed before <see cref="Dispose()"/>.</param>
```

Inside the constructor of `Face`.

Guess what I did.
