### ISSUE TITLE
Remove the confusing description "Cross-Platform"

### ISSUE THREAD

**Issue by dawiddyrcz** [Robmaister/SharpFont#134]
Please remove the confusing description "Cross-Platform" from nuget-packages and from readme, because this library is "Windows only, .net core"

**Comment by HinTak** [comment]
It is cross-platform - people use sharpfont regularly (as part of https://github.com/HinTak/Font-Validator/tree/master/bin ) on linux (both Intel/x86-64 and arm/raspberrypi) and on Mac OS X (Darwin) too. Depending on what statistics you look at, the Mac version of Font Validator is perhaps more used or more popular than the Windows version.

**Comment by Robmaister** [comment]
README includes build instructions for Mono, the library has been used in a number of cross-platform game engines as well (though with the lack of maintenance I think some of them have moved on)

**Comment by HinTak** [comment]
I released a new version of Font Validator (which uses sharpfont) a few months ago - according to the download statistics it is about 10% linux, 40% mac, 50% windows.
