### ISSUE TITLE
Powershell

### ISSUE THREAD

**Issue by AntonioTony** [Robmaister/SharpFont#40]
Hi. I will also want to thanks for this awesome work.

I was trying to add to this module a class in order to work with Powershell. 
I want to get the font name from a bunch of font files.
I don't know too much about C# and i'm trying to do make this work but i can't. I've made a lot of tests, but i can't make it to work.
I'm using the code found in the Example with little changes.

This is the code i'm using 

using System;
using System.Collections.Generic;
//using System.Linq;
using System.Text;
using System.Management;
using System.Management.Automation;
using SharpFont;

namespace Powershell
{

    [Cmdlet(VerbsCommon.Get, "FontNames")]
    public class Get_FontNames : System.Management.Automation.PSCmdlet
    {
        [Parameter(Position = 0, Mandatory = true, HelpMessage = "The full file name of the archive")]
        [ValidateNotNullOrEmpty]
        public string ArchiveFileName { get; set; }

        //protected override void EndProcessing()

        protected override void ProcessRecord()
        {
            //TODO make several examples in an example browser

            try
            {
                using (Library lib = new Library())
                {
                    WriteObject("FreeType version: " + lib.Version + "\n", true);
                    using (Face face = lib.NewFace(@ArchiveFileName, 0))
                    {
                        WriteObject("Information for font " + face.FamilyName, true);
                        WriteObject("Information for font " + face.GetPostscriptName(), true);
                        WriteObject("====================================", true);
                        WriteObject("Number of faces: " + face.FaceCount, true);
                        WriteObject("Face flags: " + face.FaceFlags, true);
                        WriteObject("Style: " + face.StyleName, true);
                        WriteObject("Style flags: " + face.StyleFlags, true);
                    }
                }
            }
            catch (FreeTypeException e)
            {
                WriteObject(e.Error.ToString(), true);
            }

        }
    }
}
I don't what  I'm doing wrong.
Any help, would be appreciated.

Thank you

**Comment by Robmaister** [comment]
Update: SharpFont now supports x64 as well, so long as you follow the Examples project to set the proper DLL directory!
