### ISSUE TITLE
Kerning Issue in Example Code

### ISSUE THREAD

**Issue by killowatt** [Robmaister/SharpFont#51]
I am having this issue with the example code. The kerning on the A is messed up.

![Image1](http://i.imgur.com/k2WQoUs.png) (using DIN font)
![Image2](http://i.imgur.com/K1BnpEV.png)
 (using included font)

This is using my own font and the included font in the example code provided in the repo. I have tried one of the release versions and many versions of the freetype dll, but this issue persists. Again, this is using the example code provided by the repo.

**Comment by Robmaister** [comment]
In that case the example code is probably broken. If you could email me the font that's currently broken it would be helpful in verifying that the issue is fixed.

It's probably a pretty simple bug. Ping me again in a few days if I don't have a fix.

**Comment by killowatt** [comment]
Ping pong.

**Comment by Robmaister** [comment]
Sorry about the delay. Neither the DIN font nor the Cousine font are being detected as fonts with kerning, which is strange. Looking into it more right now.

**Comment by Robmaister** [comment]
Looks like Face.GetKerning is returning (0, 0), likely as a result of the recent switch to special structs for 16.16 /  26.6 values. Should have a fix soon.

**Comment by Robmaister** [comment]
So naturally my original thoughts were wrong. I found that there were actually no kerning pairs in either font. Turns out that this line:

    g.DrawImageUnscaled(cBmp, (int)Math.Round(penX), (int)Math.Round(penY + (bmp.Height - face.Glyph.BitmapTop)));

should have been

    g.DrawImageUnscaled(cBmp, (int)Math.Round(penX + face.Glyph.BitmapLeft), (int)Math.Round(penY + (bmp.Height - face.Glyph.BitmapTop)));

I also found a bunch of things that were slightly incorrect through the whole process, so it wasn't entirely a waste.
