### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by emersont1** [Robmaister/SharpFont#59]
is there any online docs for this project or is it based on freetype?

**Comment by Robmaister** [comment]
SharpFont is a wrapper around freetype, which means that it actually calls freetype internally. It just has a C# style API. So no online docs as of now.

You can look at existing code that uses freetype and pretty easily use SharpFont. The main difference is that SharpFont makes it look object oriented and turns the error return values into Exceptions. Init/Destroy functions are handled by the constructor and GC (or Dispose), etc.

**Comment by Robmaister** [comment]
Source code should also be a pretty good resource, it's all pretty clean and has all the freetype documentation as inline doc comments.

**Comment by emersont1** [comment]
Okay. Thank you very much

**Comment by emersont1** [comment]
Could the library do with some examples?

**Comment by Robmaister** [comment]
Yes, there is one example which does basic rendering of fonts with GDI+

https://github.com/Robmaister/SharpFont/tree/master/Source/Examples
