### ISSUE TITLE
Example output has the glyph descender cutted

### ISSUE THREAD

**Issue by midiway** [Robmaister/SharpFont#60]
![untitled-1](https://cloud.githubusercontent.com/assets/493743/11610285/fa3bf630-9b84-11e5-968d-584a56207247.png)
See, that is something that needs to be patched in Program.RenderString() method to account glyph descender height

**Comment by Robmaister** [comment]
Yep, I'm aware of the issue and added that font in particular because of the issue. Just haven't had the time to fix a minor bug like this.

Thanks for the reminder, though. It should be a fairly simple fix.

**Comment by midiway** [comment]
How do I know if a given GlyphSlot has a descender?

**Comment by Robmaister** [comment]
Descenders in fonts are not exposed in a uniform way. If you're looking to line things up to a baseline, it should be `height - horizontalBearingY`.

Also I'm working on fixing the text rendering in Examples right now. Should be up within the hour.

**Comment by Robmaister** [comment]
(turns out those bugs were actually the result of me using the last release of SharpFont instead of master, oops)
