### ISSUE TITLE
Nuget package installation fail after Visual Studio Community 2015 Update 1

### ISSUE THREAD

**Issue by GrafSeismo** [Robmaister/SharpFont#61]
Just tried to install current package into a new universal windows project to get a monogame pipline to work but installation got rejected.

Microsoft Visual Studio Community 2015
Version 14.0.24720.00 Update 1
Microsoft .NET Framework
Version 4.6.01038

Installed Version: Community
Visual C# 2015   00322-20000-00000-AA031
Microsoft Visual C# 2015
NuGet Package Manager   3.3.0
Visual Studio Tools for Universal Windows Apps   14.0.24720.00

**Comment by Robmaister** [comment]
What was the error message you received when you tried to install and it was rejected?

If you don't see a specific one, try installing it from the *Package Manager Console* in Visual Studio, or from a regular command line with nuget.exe

**Comment by GrafSeismo** [comment]
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0.
Some packages are not compatible with UAP,Version=v10.0.
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0 (win10-arm).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm).
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0 (win10-arm-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-arm-aot).
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x86).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86).
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x86-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x86-aot).
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x64).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64).
SharpFont 3.0.1 is not compatible with UAP,Version=v10.0 (win10-x64-aot).
Some packages are not compatible with UAP,Version=v10.0 (win10-x64-aot).

i have Windows SDK 10.0.10586.15 installed.

**Comment by Robmaister** [comment]
After a small amount of searching, it looks as though there are some parts of the SharpFont API that are not compatible with the Universal Windows Platform. This will require some work to identify and then fix.

For now it should work with a project targeting .NET Core or Client Profile. (2.0+). I'll start scoping this out today

**Comment by GrafSeismo** [comment]
The "incompatibility" comes from .NETCore, mostly the Serialisation part is away, Reflection changed dramatic and Filemanagement is encapsulated in StorageFile. I just collect the differencies in detail for myself, it seems that many projects need to do this steps now.

**Comment by Robmaister** [comment]
PR #80 adds support for .NET Core among other platforms, I'll close this once I release the next version on NuGet.

**Comment by Robmaister** [comment]
@GrafSeismo Finally got around to releasing 4.0.0 with new platform support. I'll leave this open to let you test

**Comment by GrafSeismo** [comment]
I am sorry, but i had some issues in my life that prevent me currently to develop with the necessary time. I hope you will find another tester!

**Comment by Robmaister** [comment]
No worries, open another issue if you run into a new problem
