### ISSUE TITLE
Exception when loading Sfnt tables

### ISSUE THREAD

**Issue by opcon** [Robmaister/SharpFont#77]
Attempting to load Sfnt font tables fails with the following exception:

``` Cannot marshal field 'Created' of type 'SharpFont.TrueType.Internal.HeaderRec': Invalid managed/unmanaged type combination (Array fields must be paired with ByValArray or SafeArray). ```

**Comment by Robmaister** [comment]
This should be fixed but in a different way through #80, I'll leave it open until you get a chance to test it. Updated NuGet package should be up at some point this weekend.

**Comment by opcon** [comment]
#80 fixes it, thank you :)

I noticed that #80 changed the minimum .NET framework to 4.5 for the SharpFont project.
The SharpFont project still compiles fine with 3.5 and 4.0, both of which will provide greater compatibility.

**Comment by Robmaister** [comment]
Perhaps it's related to .NET Core support? I can try messing around with the csproj file to add a .NET 3.5 target if necessary... 4.5 adoption may be wide enough that it won't be worth my time to write. I'll look into it

**Comment by opcon** [comment]
It already compiles fine with 3.5 and up, the target framework version just needs changing in the SharpFont project :) 

This shouldn't affect the portable or ios projects either

**Comment by Robmaister** [comment]
Yeah I'm more looking more in terms of distribution. For example, OpenRA just recently updated to 4.5, would they need to also install .NET 3.5 alongside 4.5 for just the one dependency or will it run in a 4.5 environment by itself?

If not, would I have to distribute separate 3.5 and 4.5 NuGet packages?

**Comment by opcon** [comment]
Sorry, I understand now. Components (class libraries) will run on whichever framework the application using them runs on, no matter what they were compiled with, according to [this](https://msdn.microsoft.com/en-us/library/ff602939%28v=vs.110%29.aspx#Anchor_1). There may be some subtle changes between framework and CLR versions though.

I understand your concern, and I now realise that targeting 4.5 is not so bad, since Windows 8 ships with it by default. The only thing you really lose is Windows XP support, which only supports up to 4.0.

I'll close this, supporting 4.5 and up is fine :)

**Comment by Robmaister** [comment]
Ah that makes sense, I was wondering what a lot of other large projects would do in this case and it's nice to see that it pretty much "just works" on the .NET side :smile:
