### ISSUE TITLE
License

### ISSUE THREAD

**Issue by rapgro** [Robmaister/SharpFont#92]
These files are without license header:
SharpFont-3.1.0/Source/Examples/ExampleForm.Designer.cs
SharpFont-3.1.0/Source/Examples/ExampleForm.cs
SharpFont-3.1.0/Source/Examples/Forms/LabeledToolStripComboBox.Designer.cs
SharpFont-3.1.0/Source/Examples/Forms/LabeledToolStripComboBox.cs
SharpFont-3.1.0/Source/Examples/Properties/AssemblyInfo.cs
SharpFont-3.1.0/Source/SharpFont/Properties/AssemblyInfo.cs

**Comment by Robmaister** [comment]
Thanks for the catch, should be fixed in a second.

**Comment by Robmaister** [comment]
The latest version of /Source/Examples/ExampleForm.cs already has a header. The rest are added.
