### ISSUE TITLE
glyph metrics values

### ISSUE THREAD

**Issue by pdx-one** [Robmaister/SharpFont#94]
Hi,

i want receive the glyph metrics SharpFont, but i have some little troubles with.

within following steps:

1. load Face(*.ttf)
2. set CharSize(32)
3. get glyph-index by given char
3. load Glyph with default options.
4. read outline-points with line, conic and cubic segments (mulitplicate point-size(64))
5. render through open-gl

resulting to an midsize glyph display-output through a opengl-window.

now i want to receive glyph-metrics, but the values wide different from that of the outline-points, got 0.0floating outline-points, and metrics of 1000integral values. i dont know how to translate these width, advance, bearing metrics to compilant values for the outline points. or in the phython api these values are similar to.

post from freetype-mailing list with test-results, in these case all is correct

> now i want to receive glyph-metrics, but the values wide different
> from that of the outline-points ...

    import sys
    import qahirah as qah
    import freetype2
    from freetype2 import \
        FT
    ft = qah.get_ft_lib()

    face = ft.find_face("Palatino")
    sys.stderr.write("Using font %s %s from %s\n" % (face.family_name, face.style_name, face.filename))
    face.set_char_size(size = 32, resolution = qah.base_dpi)
    glyph_index = face.get_char_index(ord("W"))
    face.load_glyph(glyph_index, FT.LOAD_DEFAULT)
    sys.stdout.write("glyph %d metrics = %s, outline bbox = %s\n" % (glyph_index, face.glyph.metrics, face.glyph.outline.get_bbox()))

and got the following output on my system:

    Using font URW Palladio L Roman from /usr/share/fonts/type1/gsfonts/p052003l.pfb
    glyph 56 metrics = {'vertBearingX': 0.0, 'horiBearingX': 0.0, 'horiAdvance': 32.0, 'height': 22.0, 'horiBearingY': 22.0, 'vertAdvance': 0.0, 'vertBearingY': 0.0, 'width': 31.0}, outline bbox = BBox(0.250, 0.000, 30.859, 22.000)

please help. need right value translation. think may bug issue

thx pdx

**Comment by HinTak** [comment]
You do know that you are asking questions about freetype's python binding in the issue tracker of freetype's c# binding, right? You probably should post to the py-freetype list instead.

That said, what are you trying to do? Glyph metric values are either in output pixel/point units (your 32), in logical unit of the glyph unit box (1000 or 2048, depending on the font type), or F16.16, F26.6, etc - you need to read the doc. The F16.16 etc unit is a special representation of floating point numbers in a 32-bit integer, etc.

As I said, you should reading post to py-freetype instead.

**Comment by pdx-one** [comment]
hello, thanks for your answer, and for nothing else., sorry.

these binding is not CONSISTENT, plain c-api and python api works.

may causing of linking depencies, i dont know. work now with own simple direct c-binding.

thx pdx

**Comment by HinTak** [comment]
I am not sure what you aretrying to say here - if you like the direct c-api and py-freetype, please feel free to do so. It is just very bizzarre of you asking questions about py-freetype here . Your code above is python code, you realize, right? SharpFont is a C# binding. If you have python questions, you should ask elsewhere, not here.

If you are genuinely trying to get C# code to work, and failing, here is some tips, and see also L399, and L146 to L162, L304 to L318 of this file, besides L168.
https://github.com/HinTak/Font-Validator/blob/master/Compat/Compat.cs#L168
note the use of `new Fixed16Dot16())` . The C# binding is closer to the C-binding than the python one.

**Comment by Robmaister** [comment]
Hey pdx,

SharpFont is a fairly direct wrapping of the FreeType2 API, just spread out into classes and with built-in error checking.

There have been a few extra additions to help new users out and to avoid unnecessary math. One of those things are FixedXDotY structs that automatically convert the fixed-point numbers to standard C# numeric types.

You can use the `.Value` property to retrieve the raw bits that other bindings and the original API return. You can also cast to a float, double, or decimal or call `ToFloat()`, `ToDouble()`, or `ToDecimal()` to get the metrics that the Python bindings appear to give.

Sorry about the confusion,
Robert

**Comment by pdx-one** [comment]
thanks for your answer(s). 

c-api works fine, :|

**Comment by HinTak** [comment]
For example, I am fairly sure your L82 is wrong:
https://github.com/pdx-one/UndefinedProject/blob/master/be_charp/be_ui/Types/Font.cs#L82

Here is the correct usage of `SetCharSize`:
https://github.com/HinTak/Font-Validator/blob/master/Compat/Compat.cs#L168

And here is the C-API reference for `FT_Set_Char_Size`:
https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#FT_Set_Char_Size

And another thing is - it should not be me doing a reverse-look-up on what your C# project you are doing. You should have pointed us to your own buggy C# code, instead of some python code. Your python code is not helping your lack of c# skills.

**Comment by pdx-one** [comment]
in example-project using such as.

is also not matter now. have more advantages to the c-api also

**Comment by HinTak** [comment]
If you are not showing your buggy C# code, it is almost impossible to help you.

**Comment by pdx-one** [comment]
at this point is fine soluted, faces-size in pixel is in case of horiziontal and vertical, vertical floating point orienteted., c-api works.

**Comment by pdx-one** [comment]
you do not like me, not even you're right.

**Comment by pdx-one** [comment]
bla

**Comment by HinTak** [comment]
And please mind your use of English, if you want any help at all. You will not get help if you use swear words in every other sentences.

**Comment by pdx-one** [comment]
native-like

**Comment by pdx-one** [comment]
you know system and abstract

**Comment by pdx-one** [comment]
fucking idiot looser mio.

**Comment by pdx-one** [comment]
translate back. kiddy

**Comment by pdx-one** [comment]
you stupid, cheap system-binding, for c# system-language, thats strange, not working for me

**Comment by pdx-one** [comment]
killing

**Comment by pdx-one** [comment]
physics, 20-or-even-30 features, you single-one, stupid-o-no-one

bla

**Comment by pdx-one** [comment]
test my full-featured language, system-abstract, not at this point, c#/java full referenced, 8000 lines, thats gen.

**Comment by pdx-one** [comment]
simple naiv idiot

**Comment by Robmaister** [comment]
This is unacceptable behavior and language - I'm locking this issue and redacting swear words.

We're trying to help you, it's unlikely that this part of the API is incorrect as it's a relatively central part of it, and none of the other thousands of users have complained.

If you'd like some help, please open another issue with a MCVE - http://stackoverflow.com/help/mcve in C# using SharpFont, showing the incorrect values.

If you continue this behavior in a new issue/PR, I will block you.
