### ISSUE TITLE
Linq and .net2 compatibility of 4.X+

### ISSUE THREAD

**Issue by HinTak** [Robmaister/SharpFont#95]
A while ago I noted that 4.0 no longer build with .net2 profile, due to the introduction of some Linq constructs, I think. Quite fixable, I just haven't got time to try. Somebody else please feel free to beat me to fixing this.

**Comment by Robmaister** [comment]
Any particular reason to still explicitly support .NET 2.0? Pretty sure all our downstreams are targeting 4.0+, and even the really stable (Ubuntu LTS, RHEL) Linux distros are distributing Mono 2.10.8, which knows about LINQ and can compile C# 4.0 syntax just fine.

I would hold off on this until there was an explicit need from someone, which seems really unlikely to me. Even legacy applications should be able to run on a modern version of .NET

**Comment by HinTak** [comment]
Net 3.X and 4.X don't run(install?) well under wine. So where mono is inadequate - mixed mode assembly, the system.security name space, or winform etc - one still needs to use wine and genuine dotnet, instead of native mono.

**Comment by Robmaister** [comment]
From a quick search, it appears as though most versions of .NET install and run at the very least decently with the use of winetricks.

If there is some set of configurations causing problems, you can still make it work through the use of LinqBridge, or just copying System.Core.dll into the output path.

http://stackoverflow.com/questions/2138/linq-on-the-net-2-0-runtime

I'm mostly hesitant about this because I see little benefit in bloating up parts of the library to support a 14 year old, end-of-life runtime. The LINQ statements are very concise. I believe the solution for you lies in either fixing the problems that WINE has with old .NET or using a LINQ backport, both of which don't seem like far-off solutions.

**Comment by Robmaister** [comment]
Currently the only thing that isn't compiling properly when targeting .NET 2.0 at the moment is the use of [`GetRuntimeProperty`](https://msdn.microsoft.com/en-us/library/system.reflection.runtimereflectionextensions.getruntimeproperty(v=vs.110).aspx) in FT.IsMacOS.

@corliss is there a way to make this work? I'm looking into it, and it appears as though this function replaces `GetProperty`, but that WinRT needs it to work properly.

**Comment by HinTak** [comment]
@Robmaister @corliss That  FT.IsMacOS is implementation is bizarre. I don't know why you need to do a lock and reflection on the type. You can test for `Environment.OSVersion.Platform == PlatformID.MacOSX` plain. This is known not to work in runtine 1.0/1.1, when OS X would be lumped under unix instead of having its own Platform ID away from unix from 2.0 onward.

This is from one of Mono's own FAQ. (how to test for Mac OS X).

**Comment by corliss** [comment]
@Robmaister - I am getting a bit tired of these rude comments. This person does not know how to speak politely, contributes nothing, and doesn't even try out his "suggestions" before making them. If you can't remove him from these discussions I don't want to be a part of them. 'Nuff said.

**Comment by HinTak** [comment]
Rather bizarre request to remove the initial filer of an issue. May I suggest people not to comment on issue.  other filed if they have thin skins?

**Comment by HinTak** [comment]
@Robmaister : since we are in "making bizarre demands" territory, let me say this once: if you merge bizarre changes from bizarre individuals which breaks other contributors' existing usage of SharpFont, you are asking other contributors to stop contributing or even looking at upstream, but just keep using an older (fork of) SharpFont. Not upgrading is always a lot easier than trying to cope with random bizarre additions.

@corliss

**Comment by HinTak** [comment]
I have back-ported the linq removal and the streaming interface to my branch off v4.0.1:

https://github.com/HinTak/SharpFont/tree/v4.0.1+fixes

net2 support was the one thing that was blocking my upgrade from v3.x so at least that's done. SharpFont HEAD is very broken as far as building with mono goes. So I am not touching it until it looks like it is getting fixed. For now, my v4.0.1+fixes branch is buildable with mono, to run on a net2 runtime.

**Comment by Robmaister** [comment]
Yeah, merging the projects back together and applying csproj hacks for .NET 2/.NET 4.5/PCL builds seems to have caused more trouble than it was worth. I'll probably be reverting that change and adding solution folders for the shared project + specific target csproj files for cleanliness. iOS builds appear entirely broken, looks like we have to use the preprocessor to switch to "__Internal" with no other options. I can't find any project/documentation on any other technique, and I've searched for a while.

I do like the idea of limiting the use of the preprocessor with regards to the OS X specific functionality, but the example in the Mono FAQ apparently has troubles detecting OS X vs Linux. Some other projects (OpenTK, MonoDevelop, among others) have chosen to pull from `uname()` directly if on a non-Windows OS. We may want to copy (with attribution, of course) this technique:

https://github.com/opentk/opentk/blob/develop/src/OpenTK/Configuration.cs

Some relevant threads:
http://mono.1490590.n4.nabble.com/Why-does-Environment-OSVersion-Platform-report-PlatformID-Unix-on-OS-X-td4038093.html
http://mono.1490590.n4.nabble.com/Howto-detect-os-td1549244.html

Does this approach sound reasonable?

**Comment by HinTak** [comment]
Okay. The mac os x specific platform Id was reverted in January 2011, so the FAQ is outdated. Calling uname in libc is ugly. If you are going to

**Comment by HinTak** [comment]
Linq was removed post v4.0 at V4.0 + 16 : 
https://github.com/Robmaister/SharpFont/commit/54be8c7e526b878b2d7ff462de0ffa0bd756ee7b

**Comment by HinTak** [comment]
Closing issues which is no longer a problem as I make another release of my software based on patched SharpFont v4.0.
