### ISSUE TITLE
method Face#GetPSFontInfo(), Face#GetPSFrivate still throw exception

### ISSUE THREAD

**Issue by NguyenNghiaUIT** [Robmaister/SharpFont#97]

**Comment by Robmaister** [comment]
Since this is related to #96, please keep it on the same issue.

**Comment by NguyenNghiaUIT** [comment]
Yes, Thanks, and you can build a new version for SharpFont Library on Nuget?

**Comment by Robmaister** [comment]
Yup, SharpFont 4.1.0 should be on NuGet within a week. I'm going to take care of a few other issues/PRs and add in all the FreeType 2.6 + 2.7 APIs before I do.
