### ISSUE TITLE
How do I know if a Glyph has a descender?

### ISSUE THREAD

**Issue by midiway** [Robmaister/SharpFont#98]
```
float descender = _face.Size.Metrics.Descender.ToSingle();// always negative
..
_face.LoadGlyph(glyphIndex, LoadFlags.Default, LoadTarget.Normal);
bool hasDescender = _face.Glyph.HasDescender; //???
```
![http://facweb.cs.depaul.edu/sgrais/images/4Sculptures/Type2.4.gif](http://facweb.cs.depaul.edu/sgrais/images/4Sculptures/Type2.4.gif)

Wish there was a HasDescender property of the Glyph. Or is there another way to know it?

**Comment by HinTak** [comment]
See the comment about `GetCBox` in `Source/SharpFont/Glyph.cs` ; that may be good enough for your purpose.  You check if `bbox.yMin` is less than zero.
